# Generated by Django 4.0.5 on 2022-07-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='autor',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas'),
        ),
    ]
